### ISSUE TITLE
EventData: custom update for 'or' 'and'

### ISSUE THREAD

**Issue by vjdorazio** [TwoRavens/TwoRavens#272] opened 2018-05-29 18:58 UTC
In `subset`, if I stage two queries and then change `and` to `or`, and then click on "Custom", it doesn't look like the default `and` changes to `or`.

**Comment by Shoeboxam** [comment] 2019-05-31 00:01
I could never reproduce this, but have since rewritten trees in experimental. I still cannot reproduce. Closing.

**Closed by Shoeboxam** 2019-05-31 00:01 UTC
Labels: EventData
